USE [SQL-PRACTICALS]

CREATE TABLE STUDENT
(
STUID INT,
FIRSTNAME VARCHAR(25),
LASTNAME VARCHAR(25),
WEBSITE VARCHAR(25),
CITY VARCHAR(25)
)

INSERT INTO STUDENT (STUID,FIRSTNAME,LASTNAME,WEBSITE,CITY)
VALUES
(1011,'KEYUR','PATEL','TECHONTHENET.COM','RAJKOT'),
(1022,'HARDIK','SHAH','DIGMINECRAFT.COM','AHMEDABAD'),
(1033,'KAJAL','TRIVEDI','BIGACTIVITIES.COM','BARODA'),
(1044,'BHOOMI','GAJERA','CHECKYOURMATH.COM','AHMEDABAD'),
(1055,'HARMIT','MITEL',NULL,'RAJKOT'),
(1066,'ASHOK','JANI',NULL,'BARODA')

SELECT * FROM STUDENT

--------------------------------------PART - A--------------------------------------

SELECT FIRSTNAME FROM STUDENT
WHERE
FIRSTNAME LIKE'K%'

SELECT FIRSTNAME FROM STUDENT
WHERE
FIRSTNAME LIKE '_____'

SELECT FIRSTNAME,LASTNAME FROM STUDENT
WHERE
CITY LIKE '%A' AND CITY LIKE '______'

SELECT * FROM STUDENT
WHERE
LASTNAME LIKE '%TEL'

SELECT * FROM STUDENT
WHERE
FIRSTNAME LIKE 'HA%T'

SELECT * FROM STUDENT
WHERE
FIRSTNAME LIKE 'K_Y%'

--------------------------------------PART - B--------------------------------------

SELECT FIRSTNAME FROM STUDENT
WHERE
FIRSTNAME LIKE '_____' AND WEBSITE IS NULL

SELECT * FROM STUDENT
WHERE
LASTNAME LIKE '%JER%'

SELECT * FROM STUDENT
WHERE
CITY LIKE 'R%' OR CITY LIKE 'B%'

SELECT FIRSTNAME FROM STUDENT
WHERE NOT
WEBSITE IS NULL

SELECT * FROM STUDENT
WHERE
FIRSTNAME LIKE '[ABCDEFGH]%'

SELECT * FROM STUDENT
WHERE
FIRSTNAME LIKE '_[AEIOU]%'

--------------------------------------PART - C--------------------------------------

SELECT FIRSTNAME FROM STUDENT
WHERE
WEBSITE IS NULL AND FIRSTNAME LIKE '_____%'

SELECT * FROM STUDENT
WHERE LASTNAME LIKE 'PAT%'

SELECT * FROM STUDENT
WHERE
CITY NOT LIKE 'B%'

SELECT * FROM STUDENT
WHERE 
FIRSTNAME LIKE '[ABCDEFGH]%'

SELECT * FROM STUDENT
WHERE
FIRSTNAME LIKE 'H[AEIOU]%'