USE [SQL-PRACTICALS]

CREATE TABLE STUDENT
(
ENROLLMENT_NO VARCHAR(20),
NAME VARCHAR(20),
CPI DECIMAL(5,2),
BIRTHDATE DATETIME
)

SELECT * FROM STUDENT

--------------------------------------PART - A--------------------------------------

ALTER TABLE STUDENT
ADD CITY VARCHAR(20),
BACKLOG INT

ALTER TABLE STUDENT
ALTER COLUMN NAME VARCHAR(35)

ALTER TABLE STUDENT
ALTER COLUMN CPI INT

EXEC SP_RENAME 'STUDENT.ENROLLMENT_NO', 'ENO', 'COLUMN'

ALTER TABLE STUDENT 
DROP COLUMN CITY

EXEC SP_RENAME 'STUDENT','STUDENT_MASTER'

DROP TABLE STUDENT_MASTER

--------------------------------------PART - B--------------------------------------

CREATE TABLE DEPOSIT
(
ACTNO INT,
CNAME VARCHAR(50),
BNAME VARCHAR(50), 
AMOUNT DECIMAL(8,2), 
ADATE DATETIME 
)

SELECT * FROM DEPOSIT

ALTER TABLE DEPOSIT
ADD CITY VARCHAR(20),
PINCODE INT

ALTER TABLE DEPOSIT
ALTER COLUMN CNAME VARCHAR(35)

ALTER TABLE DEPOSIT
ALTER COLUMN AMOUNT INT

EXEC SP_RENAME 'DEPOSIT.ACTNO','ANO','COLUMN'

ALTER TABLE DEPOSIT
DROP COLUMN CITY

--------------------------------------PART - C--------------------------------------

ALTER TABLE DEPOSIT
DROP COLUMN ADATE

EXEC SP_RENAME 'DEPOSIT.CNAME','CUSTOMERNAME','COLUMN'

EXEC SP_RENAME 'DEPOSIT','DEPOSIT_DETAIL'

DROP TABLE DEPOSIT_DETAIL